### ISSUE TITLE
Issues when polls is close.

### ISSUE THREAD

**Issue by KunKid-cmd** [SmileyFaceZ/ku-polls#45]
Issues when i make an end date in admin page when i go back to polls and click the results button it show me "Page not found"
<img width="976" alt="ภาพถ่ายหน้าจอ 2566-09-23 เวลา 13 54 36" src="https://github.com/SmileyFaceZ/ku-polls/assets/115053938/e4b89f8a-9916-4f9d-b73e-26d2f8310d68">

**Comment by SmileyFaceZ** [comment]
I Implement already, it can go to a index page when not have a available poll result
